In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('movies_credits.csv')

C:\Users\pablo\AppData\Local\Temp\ipykernel_14964\3187682485.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('movies_credits.csv')

In [3]:
df

,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,...,status,tagline,title,vote_average,vote_count,release_year,return,name_collection,cast,Director
0,30000000.0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar Animation Studios,United States of America,1995-10-30,373554033.0,...,Released,sin datos,Toy Story,7.7,5415.0,1995,12.451801,Toy Story Collection,"Tom Hanks, Tim Allen, Don Rickles, Jim Varney,...",John Lasseter
1,65000000.0,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"TriStar Pictures, Teitler Film, Interscope Com...",United States of America,1995-12-15,262797249.0,...,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,1995,4.043035,sin datos,"Robin Williams, Jonathan Hyde, Kirsten Dunst, ...",Joe Johnston
2,0.0,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,11.7129,"Warner Bros., Lancaster Gate",United States of America,1995-12-22,0.0,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,1995,0.000000,Grumpy Old Men Collection,"Walter Matthau, Jack Lemmon, Ann-Margret, Soph...",Howard Deutch
3,16000000.0,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156.0,...,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,1995,5.090760,sin datos,"Whitney Houston, Angela Bassett, Loretta Devin...",Forest Whitaker
4,0.0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,"Sandollar Productions, Touchstone Pictures",United States of America,1995-02-10,76578911.0,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,1995,0.000000,Father of the Bride Collection,"Steve Martin, Diane Keaton, Martin Short, Kimb...",Charles Shyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45448,0.0,"Drama, Action, Romance",30840,en,"Yet another version of the classic epic, with ...",5.683753,"Westdeutscher Rundfunk (WDR), Working Title Fi...","Canada, Germany, United Kingdom, United States...",1991-05-13,0.0,...,Released,sin datos,Robin Hood,5.7,26.0,1991,0.000000,sin datos,"Patrick Bergin, Uma Thurman, David Morrissey, ...",John Irvin
45449,0.0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,Sine Olivia,Philippines,2011-11-17,0.0,...,Released,sin datos,Century of Birthing,9.0,3.0,2011,0.000000,sin datos,"Angel Aquino, Perry Dizon, Hazel Orencio, Joel...",Lav Diaz
45450,0.0,"Action, Drama, Thriller",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,American World Pictures,United States of America,2003-08-01,0.0,...,Released,A deadly game of wits.,Betrayal,3.8,6.0,2003,0.000000,sin datos,"Erika Eleniak, Adam Baldwin, Julie du Page, Ja...",Mark L. Lester
45451,0.0,sin datos,227506,en,"In a small town live two brothers, one a minis...",0.003503,Yermoliev,Russia,1917-10-21,0.0,...,Released,sin datos,Satan Triumphant,0.0,0.0,1917,0.000000,sin datos,"Iwan Mosschuchin, Nathalie Lissenko, Pavel Pav...",Yakov Protazanov
45452,0.0,sin datos,461257,en,50 years after decriminalisation of homosexual...,0.163015,sin datos,United Kingdom,2017-06-09,0.0,...,Released,sin datos,Queerama,0.0,0.0,2017,0.000000,sin datos,sin datos,Daisy Asquith

In [4]:
import nltk

In [5]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [6]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [7]:
df.cast = df.cast.str.replace(" ", "").str.replace(",", ", ")

In [8]:
df.cast

0        TomHanks, TimAllen, DonRickles, JimVarney, Wal...
1        RobinWilliams, JonathanHyde, KirstenDunst, Bra...
2        WalterMatthau, JackLemmon, Ann-Margret, Sophia...
3        WhitneyHouston, AngelaBassett, LorettaDevine, ...
4        SteveMartin, DianeKeaton, MartinShort, Kimberl...
                               ...
45448    PatrickBergin, UmaThurman, DavidMorrissey, Jür...
45449    AngelAquino, PerryDizon, HazelOrencio, JoelTor...
45450    ErikaEleniak, AdamBaldwin, JulieduPage, JamesR...
45451    IwanMosschuchin, NathalieLissenko, PavelPavlov...
45452                                             sindatos
Name: cast, Length: 45453, dtype: object

In [9]:
df.Director = df.Director.str.replace(" ", "")

In [10]:
df

,budget,genres,id,original_language,overview,popularity,production_companies,production_countries,release_date,revenue,...,status,tagline,title,vote_average,vote_count,release_year,return,name_collection,cast,Director
0,30000000.0,"Animation, Comedy, Family",862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,Pixar Animation Studios,United States of America,1995-10-30,373554033.0,...,Released,sin datos,Toy Story,7.7,5415.0,1995,12.451801,Toy Story Collection,"TomHanks, TimAllen, DonRickles, JimVarney, Wal...",JohnLasseter
1,65000000.0,"Adventure, Fantasy, Family",8844,en,When siblings Judy and Peter discover an encha...,17.015539,"TriStar Pictures, Teitler Film, Interscope Com...",United States of America,1995-12-15,262797249.0,...,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413.0,1995,4.043035,sin datos,"RobinWilliams, JonathanHyde, KirstenDunst, Bra...",JoeJohnston
2,0.0,"Romance, Comedy",15602,en,A family wedding reignites the ancient feud be...,11.7129,"Warner Bros., Lancaster Gate",United States of America,1995-12-22,0.0,...,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92.0,1995,0.000000,Grumpy Old Men Collection,"WalterMatthau, JackLemmon, Ann-Margret, Sophia...",HowardDeutch
3,16000000.0,"Comedy, Drama, Romance",31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,Twentieth Century Fox Film Corporation,United States of America,1995-12-22,81452156.0,...,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34.0,1995,5.090760,sin datos,"WhitneyHouston, AngelaBassett, LorettaDevine, ...",ForestWhitaker
4,0.0,Comedy,11862,en,Just when George Banks has recovered from his ...,8.387519,"Sandollar Productions, Touchstone Pictures",United States of America,1995-02-10,76578911.0,...,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173.0,1995,0.000000,Father of the Bride Collection,"SteveMartin, DianeKeaton, MartinShort, Kimberl...",CharlesShyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45448,0.0,"Drama, Action, Romance",30840,en,"Yet another version of the classic epic, with ...",5.683753,"Westdeutscher Rundfunk (WDR), Working Title Fi...","Canada, Germany, United Kingdom, United States...",1991-05-13,0.0,...,Released,sin datos,Robin Hood,5.7,26.0,1991,0.000000,sin datos,"PatrickBergin, UmaThurman, DavidMorrissey, Jür...",JohnIrvin
45449,0.0,Drama,111109,tl,An artist struggles to finish his work while a...,0.178241,Sine Olivia,Philippines,2011-11-17,0.0,...,Released,sin datos,Century of Birthing,9.0,3.0,2011,0.000000,sin datos,"AngelAquino, PerryDizon, HazelOrencio, JoelTor...",LavDiaz
45450,0.0,"Action, Drama, Thriller",67758,en,"When one of her hits goes wrong, a professiona...",0.903007,American World Pictures,United States of America,2003-08-01,0.0,...,Released,A deadly game of wits.,Betrayal,3.8,6.0,2003,0.000000,sin datos,"ErikaEleniak, AdamBaldwin, JulieduPage, JamesR...",MarkL.Lester
45451,0.0,sin datos,227506,en,"In a small town live two brothers, one a minis...",0.003503,Yermoliev,Russia,1917-10-21,0.0,...,Released,sin datos,Satan Triumphant,0.0,0.0,1917,0.000000,sin datos,"IwanMosschuchin, NathalieLissenko, PavelPavlov...",YakovProtazanov
45452,0.0,sin datos,461257,en,50 years after decriminalisation of homosexual...,0.163015,sin datos,United Kingdom,2017-06-09,0.0,...,Released,sin datos,Queerama,0.0,0.0,2017,0.000000,sin datos,sindatos,DaisyAsquith

In [11]:
df['tags'] = df['overview'] +' '+ df['genres'] + ', '+ df['cast']+ ', ' + df['Director']

In [12]:
df.tags[0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation, Comedy, Family, TomHanks, TimAllen, DonRickles, JimVarney, WallaceShawn, JohnLasseter"

In [13]:
new_df = df[['id','title','tags']]

In [14]:
new_df.tags[0]

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation, Comedy, Family, TomHanks, TimAllen, DonRickles, JimVarney, WallaceShawn, JohnLasseter"

In [15]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\pablo\AppData\Local\Temp\ipykernel_14964\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [16]:
new_df

,id,title,tags
0,862,Toy Story,"led by woody, andy's toys live happily in his ..."
1,8844,Jumanji,when siblings judy and peter discover an encha...
2,15602,Grumpier Old Men,a family wedding reignites the ancient feud be...
3,31357,Waiting to Exhale,"cheated on, mistreated and stepped on, the wom..."
4,11862,Father of the Bride Part II,just when george banks has recovered from his ...
...,...,...,...
45448,30840,Robin Hood,"yet another version of the classic epic, with ..."
45449,111109,Century of Birthing,an artist struggles to finish his work while a...
45450,67758,Betrayal,"when one of her hits goes wrong, a professiona..."
45451,227506,Satan Triumphant,"in a small town live two brothers, one a minis..."
45452,461257,Queerama,50 years after decriminalisation of homosexual...

In [17]:
new_df['tags'][0]

"led by woody, andy's toys live happily in his room until andy's birthday brings buzz lightyear onto the scene. afraid of losing his place in andy's heart, woody plots against buzz. but when circumstances separate buzz and woody from their owner, the duo eventually learns to put aside their differences. animation, comedy, family, tomhanks, timallen, donrickles, jimvarney, wallaceshawn, johnlasseter"

In [18]:
new_df['tags'][1]

"when siblings judy and peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite alan -- an adult who's been trapped inside the game for 26 years -- into their living room. alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. adventure, fantasy, family, robinwilliams, jonathanhyde, kirstendunst, bradleypierce, bonniehunt, joejohnston"

In [19]:
#new_df = new_df.iloc[:2500,:]

In [20]:
new_df.to_csv('C:/Users/pablo/OneDrive/Escritorio/Henry/Labs/Dataset/Dataset/movies_recomendacion.csv', index=False)

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')
cv.fit_transform(new_df['tags']).toarray().shape
vectors = cv.fit_transform(new_df['tags']).toarray()

import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()


def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)


new_df['tags'] = new_df['tags'].apply(stem)

from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

C:\Users\pablo\AppData\Local\Temp\ipykernel_14964\696712595.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

:

:

In [ ]:
sorted(list(enumerate(similarity[0])), reverse=True, key= lambda x:x[1])[1:6]

[(1938, 0.1625272110744002),
 (591, 0.14817355731532725),
 (448, 0.14025268244765068),
 (104, 0.13736056394868904),
 (2248, 0.13325932093055393)]

In [ ]:
def recomendar(peli):
    peli_index = new_df[new_df['title'] == peli].index[0]
    distancia = similarity[peli_index]
    peli_lista = sorted(list(enumerate(distancia)), reverse=True, key= lambda x:x[1])[1:6]
    
    
    for i in peli_lista:
        print(new_df.title[i[0]])

In [ ]:
recomendar('Toy Story')

Condorman
Window to Paris
For Love or Money
Nobody Loves Me
A Bug's Life